name: xcstrings_conversion.yml

on:
  push:
    branches:
      - main

jobs:
  # Run xcstrings conversion script.
  run_conversion:
    runs-on: ubuntu-latest
    name: Run xcstrings conversion script
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Execute script to convert JSON to xcstrings
        run: |
          python convert_to_xcstrings.py
